export function printHelp(): void {
  console.log([
    'frontier-swarm <command> [options]',
    '',
    'Commands:',
    '  plan      Build a swarm plan from --manifest and --tasks',
    '  run       Run planned jobs through the Codex CLI',
    '  resume    Resume unfinished jobs from a prior run directory',
    '  doctor    Check package resolution before launching workers',
    '  stop      Stop a run using pids.json',
    '  collect   Collect merge bundles into ready/needs-port/failed/stale buckets',
    '  continue  Build the next closed-loop wave from a run or collected merge bundle directory',
    '  next-wave Alias for continue; use after collect to prepare the next swarm backlog/policy',
    '  query     Query collected jobs, evidence, traces, semantic sidecars, and artifacts',
    '  cleanup   Safely delete collected/indexed disposable workspaces',
    '  score     Score collected patches in throwaway workspaces',
    '  tournament show/query/compare/history/feedback for strategy-tournament.json',
    '  apply     Dry-run or apply collected patch bundles',
    '  repair-links Restore local workspace package symlinks after npm installs',
    '  verify    Verify a swarm-results.json proof',
    '',
    'Useful options:',
    '  --cwd <dir> source/workspace root for run, resume, collect, continue, score, and apply',
    '  --model-policy config-default|plan|explicit',
    '  --approval never|on-request|on-failure|untrusted',
    '  --workspace current|copy|snapshot|git-worktree',
    '  --replace-workspace false|true',
    '  --write-fence audit|strict|off (default strict for copy/snapshot; audit for current/git-worktree unless overridden)',
    '  --allowed-write-policy audit|strict|off or --strict-allowed-writes (aliases for --write-fence)',
    '  --backlog <file> --recursive-backlog true|false --max-backlog-depth <n>',
    '  --collection <dir> --run <dir> --child-backlog-name <file> --write',
    '  continue and next-wave require --run <dir|swarm-results.json> or --collection <dir|collection.json>',
    '  run --closed-loop or --continue-out <dir> to collect and write continuation artifacts after a run',
    '  --continue-write --continue-collection-out <dir> for closed-loop run continuation output control',
    '  --routing-policy <file> --routing-mode fill|override|observe',
    '  --include <path> --exclude <path> --workspace-include <path> --workspace-exclude <path> --link <path>',
    '  --semantic-import --semantic-import-include <glob> --semantic-import-exclude <glob>',
    '  --semantic-import-max-files <n> --semantic-import-max-bytes <n>',
    '  --semantic-import-sidecar-max-bytes <n> --semantic-import-archive true|false',
    '  --semantic-import-expected',
    '  collect prints compact JSON by default; use collect --full for full artifacts JSON',
    '  collect writes strategy-tournament.json and tournament-adaptive-feedback.json',
    '  continue reads --routing-policy as input and writes model-routing-policy.next.json',
    '  plan/run consume model-routing-policy.next.json with --routing-policy <file>',
    '  --dependency-health=false --dependency-health-out <file>',
    '  --adaptive --adaptive-mode observe|conservative|balanced|aggressive',
    '  --adaptive-feedback <tournament-adaptive-feedback.json>',
    '  --adaptive-min-concurrency <n> --adaptive-max-concurrency <n>',
    '  --compact-logs --max-event-bytes <n> --max-stderr-bytes <n>',
    '  --context-budget-mode warn|fail|off --max-estimated-input-tokens <n>',
    '  --max-prompt-bytes <n> --max-actual-input-tokens <n>',
    '  --focused-command <cmd> --global-command <cmd>',
    '  --q <text> --symbol <name> --path <substring> --bucket <name> --semantic --lineage --readiness <view>',
    '  --semantic-edit-status conflict|portable|stale --semantic-edit-admission auto-merge-candidate|needs-port',
    '  --semantic-key <key> --semantic-identity-hash <hash> --source-identity-hash <hash>',
    '  --operation-content-hash <hash> --edit-content-hash <hash>',
    '  --max-age-hours <n|24h> --keep-failed --keep-active --compact-artifacts --collection <dir> --write',
    '  --package-root <dir> --exclude-package <name> --write --replace',
    '  --resume-overlay <file> --include-failed=false --include-blocked=false',
    '',
    'Workers write last-message.md, codex-events.jsonl, resource-allocation.json,',
    'merge.json, changes.patch, dependency-health.json, and discovered debug/replay/watchpoint/trace artifacts.'
  ].join('\n'));
}
