export function printHelp(): void {
  console.log([
    'frontier-swarm <command> [options]',
    '',
    'Commands:',
    '  plan      Build a swarm plan from --manifest and --tasks',
    '  run       Run planned jobs through the Codex CLI',
    '  doctor    Check package resolution before launching workers',
    '  stop      Stop a run using pids.json',
    '  collect   Collect merge bundles into ready/needs-port/failed/stale buckets',
    '  score     Score collected patches in throwaway workspaces',
    '  apply     Dry-run or apply collected patch bundles',
    '  repair-links Restore local workspace package symlinks after npm installs',
    '  verify    Verify a swarm-results.json proof',
    '',
    'Useful options:',
    '  --model-policy config-default|plan|explicit',
    '  --approval never|on-request|on-failure|untrusted',
    '  --workspace current|copy|snapshot|git-worktree',
    '  --replace-workspace false|true',
    '  --include <path> --exclude <path> --link <path>',
    '  --semantic-import --semantic-import-include <glob> --semantic-import-exclude <glob>',
    '  --semantic-import-max-files <n> --semantic-import-max-bytes <n>',
    '  --semantic-import-expected',
    '  --dependency-health=false --dependency-health-out <file>',
    '  --adaptive --adaptive-mode observe|conservative|balanced|aggressive',
    '  --adaptive-min-concurrency <n> --adaptive-max-concurrency <n>',
    '  --compact-logs --max-event-bytes <n> --max-stderr-bytes <n>',
    '  --focused-command <cmd> --global-command <cmd>',
    '  --package-root <dir> --exclude-package <name> --write --replace',
    '',
    'Workers write last-message.md, codex-events.jsonl, resource-allocation.json,',
    'merge.json, changes.patch, dependency-health.json, and discovered debug/replay/watchpoint/trace artifacts.'
  ].join('\n'));
}
