import {
  FRONTIER_SWARM_DEFAULT_MODEL,
  FRONTIER_SWARM_DEFAULT_REASONING_EFFORT
} from '@shapeshift-labs/frontier-swarm';

export const FRONTIER_SWARM_CODEX_DEFAULT_MODEL = FRONTIER_SWARM_DEFAULT_MODEL;
export const FRONTIER_SWARM_CODEX_DEFAULT_REASONING_EFFORT = FRONTIER_SWARM_DEFAULT_REASONING_EFFORT;
export const FRONTIER_SWARM_CODEX_WORKSPACE_MANIFEST_KIND = 'frontier.swarm-codex.workspace-manifest';
export const FRONTIER_SWARM_CODEX_WORKSPACE_MANIFEST_VERSION = 1;
export const FRONTIER_SWARM_CODEX_WORKSPACE_PROOF_KIND = 'frontier.swarm-codex.workspace-proof';
export const FRONTIER_SWARM_CODEX_WORKSPACE_PROOF_VERSION = 1;
export const FRONTIER_SWARM_CODEX_PID_MANIFEST_KIND = 'frontier.swarm-codex.pid-manifest';
export const FRONTIER_SWARM_CODEX_PID_MANIFEST_VERSION = 1;
export const FRONTIER_SWARM_CODEX_COLLECTION_KIND = 'frontier.swarm-codex.collection';
export const FRONTIER_SWARM_CODEX_COLLECTION_VERSION = 1;
export const FRONTIER_SWARM_CODEX_APPLY_LEDGER_KIND = 'frontier.swarm-codex.apply-ledger';
export const FRONTIER_SWARM_CODEX_APPLY_LEDGER_VERSION = 1;
export const FRONTIER_SWARM_CODEX_PATCH_SCORE_KIND = 'frontier.swarm-codex.patch-score';
export const FRONTIER_SWARM_CODEX_PATCH_SCORE_VERSION = 1;
export const FRONTIER_SWARM_CODEX_SEMANTIC_IMPORT_KIND = 'frontier.swarm-codex.semantic-imports';
export const FRONTIER_SWARM_CODEX_SEMANTIC_IMPORT_VERSION = 1;
export const FRONTIER_SWARM_CODEX_JOB_EVIDENCE_KIND = 'frontier.swarm-codex.job-evidence';
export const FRONTIER_SWARM_CODEX_JOB_EVIDENCE_VERSION = 1;
export const FRONTIER_SWARM_CODEX_PATCH_INTENT_KIND = 'frontier.swarm-codex.patch-intent';
export const FRONTIER_SWARM_CODEX_PATCH_INTENT_VERSION = 1;
export const FRONTIER_SWARM_CODEX_COMPACT_DASHBOARD_KIND = 'frontier.swarm-codex.compact-dashboard';
export const FRONTIER_SWARM_CODEX_COMPACT_DASHBOARD_VERSION = 1;
export const FRONTIER_SWARM_CODEX_LINK_REPAIR_KIND = 'frontier.swarm-codex.link-repair';
export const FRONTIER_SWARM_CODEX_LINK_REPAIR_VERSION = 1;
export const FRONTIER_SWARM_CODEX_DEPENDENCY_HEALTH_KIND = 'frontier.swarm-codex.dependency-health';
export const FRONTIER_SWARM_CODEX_DEPENDENCY_HEALTH_VERSION = 1;
export const FRONTIER_SWARM_CODEX_RESUME_OVERLAY_KIND = 'frontier.swarm-codex.resume-overlay';
export const FRONTIER_SWARM_CODEX_RESUME_OVERLAY_VERSION = 1;
export const FRONTIER_SWARM_CODEX_CONTINUATION_KIND = 'frontier.swarm-codex.continuation';
export const FRONTIER_SWARM_CODEX_CONTINUATION_VERSION = 1;
export const FRONTIER_SWARM_CODEX_TOURNAMENT_QUERY_KIND = 'frontier.swarm-codex.tournament-query';
export const FRONTIER_SWARM_CODEX_TOURNAMENT_QUERY_VERSION = 1;
export const FRONTIER_SWARM_CODEX_ARTIFACT_STORE_KIND = 'frontier.swarm-codex.artifact-store';
export const FRONTIER_SWARM_CODEX_ARTIFACT_STORE_VERSION = 1;
export const FRONTIER_SWARM_CODEX_CLEANUP_PLAN_KIND = 'frontier.swarm-codex.cleanup-plan';
export const FRONTIER_SWARM_CODEX_CLEANUP_PLAN_VERSION = 1;
export const FRONTIER_SWARM_CODEX_QUERY_KIND = 'frontier.swarm-codex.query';
export const FRONTIER_SWARM_CODEX_QUERY_VERSION = 1;
export const FRONTIER_SWARM_CODEX_CONTEXT_BUDGET_KIND = 'frontier.swarm-codex.context-budget';
export const FRONTIER_SWARM_CODEX_CONTEXT_BUDGET_VERSION = 1;
export const FRONTIER_SWARM_CODEX_DASHBOARD_SNAPSHOT_KIND = 'frontier.swarm-codex.dashboard-snapshot';
export const FRONTIER_SWARM_CODEX_DASHBOARD_SNAPSHOT_VERSION = 1;
export const FRONTIER_SWARM_CODEX_STEERING_INTENT_KIND = 'frontier.swarm-codex.steering-intent';
export const FRONTIER_SWARM_CODEX_STEERING_INTENT_VERSION = 1;
export const FRONTIER_SWARM_CODEX_MODEL_TELEMETRY_KIND = 'frontier.swarm-codex.model-telemetry';
export const FRONTIER_SWARM_CODEX_MODEL_TELEMETRY_VERSION = 1;
export const FRONTIER_SWARM_CODEX_MODEL_TELEMETRY_SUMMARY_KIND = 'frontier.swarm-codex.model-telemetry-summary';
export const FRONTIER_SWARM_CODEX_MODEL_TELEMETRY_SUMMARY_VERSION = 1;
export const FRONTIER_SWARM_CODEX_HUMAN_ACTION_EVENT_KIND = 'frontier.swarm-codex.human-action-event';
export const FRONTIER_SWARM_CODEX_HUMAN_ACTION_EVENT_VERSION = 1;
export const FRONTIER_SWARM_CODEX_HUMAN_ACTION_STATE_KIND = 'frontier.swarm-codex.human-action-state';
export const FRONTIER_SWARM_CODEX_HUMAN_ACTION_STATE_VERSION = 1;
