export const DASHBOARD_WORKSPACE_PROOF_MAX_BYTES = 512 * 1024;
export const DASHBOARD_FULL_COLLECTION_MAX_BYTES = 64 * 1024 * 1024;
export const DASHBOARD_IGNORED_CHANGED_PATH_SAMPLE_LIMIT = 12;
export const DASHBOARD_QUALITY_SAMPLE_LIMIT = 12;
export const DASHBOARD_TIME_SERIES_BUCKET_MS = 60 * 1000;
